name: ml_kit_barcode_scanner_example
description: Demonstrates how to use the ml_kit_barcode_scanner plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ml_kit_barcode_scanner:
    path: ../
  cupertino_icons: ^1.0.2
  camera: ^0.8.1+4
  permission_handler: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true