name: ml_kit_barcode_scanner
description: A Flutter plugin that wraps Google ML Kit for detecting barcodes.
version: 0.1.0
authors:
  - David Serrano Canales <svprdga>

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.svprdga.ml_kit_barcode_scanner
        pluginClass: MlKitBarcodeScannerPlugin
      ios:
        pluginClass: MlKitBarcodeScannerPlugin